//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prototype.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black {
            get {
                object obj = ResourceManager.GetObject("black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blocked {
            get {
                object obj = ResourceManager.GetObject("blocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap box {
            get {
                object obj = ResourceManager.GetObject("box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap karela {
            get {
                object obj = ResourceManager.GetObject("karela", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson1 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson1 {
            get {
                return ResourceManager.GetString("Lesson1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson2 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson2 {
            get {
                return ResourceManager.GetString("Lesson2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson3 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson3 {
            get {
                return ResourceManager.GetString("Lesson3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson4 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson4 {
            get {
                return ResourceManager.GetString("Lesson4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson5 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson5 {
            get {
                return ResourceManager.GetString("Lesson5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson6 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson6 {
            get {
                return ResourceManager.GetString("Lesson6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson7 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson7 {
            get {
                return ResourceManager.GetString("Lesson7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson8 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson8 {
            get {
                return ResourceManager.GetString("Lesson8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test lesson9 body: move\r\n paint\r\n turnaround\r\n.
        /// </summary>
        internal static string Lesson9 {
            get {
                return ResourceManager.GetString("Lesson9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Karela!:
        ///Karela
        ///Karela is the robot that you can control to navigate through the grid.
        ///Blocking boxes
        ///Karela can move to any box on the grid unless you block it! Click on any box and it will turn red. When the box is red, Karela cannot move there.
        ///Running a program
        ///Once you make a program, you can run it by clicking the run button and Karela will follow the commands in your program.
        ///Step through
        ///If you want to see Karela do your commands one by one, click the step button to run your program one [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap painted {
            get {
                object obj = ResourceManager.GetObject("painted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
